seed: 42

model:
  _target_: ensemble.EnsembleEvaluator
  checkpoints: ['ckpt/164_0_8.ckpt', 'ckpt/164_end2.ckpt']
  architecture:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: utils.Block
        in_channels: 3
        out_channels: 32
        kernel_size: 3
      - _target_: utils.Block
        in_channels: 32
        out_channels: 64
        kernel_size: 3
      - _target_: utils.Block
        in_channels: 64
        out_channels: 128
        kernel_size: 3
      - _target_: utils.Block
        in_channels: 128
        out_channels: 256
        kernel_size: 3
      - _target_: torch.nn.Flatten
      - _target_: torch.nn.Linear
        in_features: 1024
        out_features: 512
      - _target_: torch.nn.ReLU
      - _target_: torch.nn.Linear
        in_features: 512
        out_features: 512
      - _target_: torch.nn.ReLU
      - _target_: torch.nn.Linear
        in_features: 512
        out_features: 10

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 1e-5

metrics:
  - _target_: torchmetrics.Accuracy
  - _target_: torchmetrics.AUROC
    num_classes: 10
  - _target_: torchmetrics.F1

datamodule:
  _target_: datamodules.CIFAR10DataModule
  data_dir: 'data/CIFAR10'
  batch_size: 64

trainer:
  log_every_n_steps: 20
  max_epochs: 100

logger:
  project: curve-fitting
  entity: distilling-object-detectors

checkpoint:
  dirpath: 'ckpt'
  monitor: Accuracy
  mode: 'max'