seed: 42

model:
  _target_: toy_model.CurveToyTrainer.load_from_checkpoint
  architecture:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: utils.Block
        in_channels: 3
        out_channels: 32
        kernel_size: 3
      - _target_: utils.Block
        in_channels: 32
        out_channels: 64
        kernel_size: 3
      - _target_: utils.Block
        in_channels: 64
        out_channels: 128
        kernel_size: 3
      - _target_: utils.Block
        in_channels: 128
        out_channels: 256
        kernel_size: 3
      - _target_: torch.nn.Flatten
      - _target_: torch.nn.Linear
        in_features: 1024
        out_features: 512
      - _target_: torch.nn.ReLU
      - _target_: torch.nn.Linear
        in_features: 512
        out_features: 512
      - _target_: torch.nn.ReLU
      - _target_: torch.nn.Linear
        in_features: 512
        out_features: 10

  checkpoint_path: 'ckpt/curve-138.ckpt'

  curve:
    start: 'ckpt/133_end1.ckpt'
    end: 'ckpt/133_end2.ckpt'
    curve_type: curves.Polyline2
  n_points: 16
  freeze_start: True
  freeze_end: True

n_batches: 10

single_model:
  _target_: toy_model.SingleToyTrainer

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 1e-5

metrics:
  - _target_: torchmetrics.Accuracy

datamodule:
  _target_: datamodules.MNISTDataModule
  data_dir: 'data/MNIST'
  batch_size: 256

trainer:
  log_every_n_steps: 20
  max_epochs: 100

logger:
  project: curve-fitting
  entity: distilling-object-detectors
